#!/usr/bin/env python3
"""Brain capture — create daily note in brain/inbox/"""

import os
from datetime import date

VAULT = "/Users/zaryu/Desktop/Niumination/brain"
INBOX = os.path.join(VAULT, "inbox")

def main():
    today = date.today()
    filename = f"{today.isoformat()}-daily.md"
    filepath = os.path.join(INBOX, filename)

    if os.path.exists(filepath):
        print(f"📋 Daily note already exists: inbox/{filename}")
        return

    content = f"""# 📝 Daily Capture — {today.isoformat()}

## ✅ Done Today

-

## 💡 Ideas

-

## 🔗 Links

-

## 📌 Notes

---

*Auto-generated by Second Brain pipeline*
"""
    with open(filepath, "w") as f:
        f.write(content.strip() + "\n")

    print(f"✅ Created: inbox/{filename}")
    print(f"📁 {filepath}")

if __name__ == "__main__":
    main()
